### ISSUE TITLE
Lines disappear before they fully leave the grid

### ISSUE THREAD

**Issue by MaxMusing** [robertcoopercode/animated-grid-lines#1]
I noticed that lines get destroyed when their "head" touches the edge of the grid. It might look better if they instead are allowed to fully leave the canvas before being destroyed.

A simple fix for this would be to virtually extend the grid beyond the edge of the canvas, by the length of the lines. In other words, don't destroy the line until the head is 5 units outside the canvas. Should be a 4-line change here:

https://github.com/robertcoopercode/animated-grid-lines/blob/0307554255195ca918b86a5e2401ee68092f60a5/src/GridRenderer.ts#L201-L214

**Comment by robertcoopercode** [comment]
Fixed this! Thanks for pointing this out @MaxMusing!
